### ISSUE TITLE
Can not install this library with PlatformIO

### ISSUE THREAD

**Issue by ArminPP** [m5stack/M5-ADS1115#1]
I tried to install this lib into PIO, but I got an error:
`PIO Core Call Error: "Resolving m5stack-atom dependencies...\r\nLibrary Manager: Installing m5stack/M5-ADS1115 @ ^0.0.2\r\n\n\nError:"`

(The installation of, for example, the M5Unit-KMeter library works)

BR, Armin

**Comment by TinyuZhao** [comment]
Fixed,https://github.com/platformio/platformio-core/issues/4430#issuecomment-1264607189
