### ISSUE TITLE
Wrong polarity?

### ISSUE THREAD

**Issue by ArminPP** [m5stack/M5-ADS1115#2]
Could it be that the input terminals are twisted? 
I get a negative voltage when I apply `GND` to the minus pin and `3.3VDC` to the plus pin.

Workaround: `int16_t adcRaw = Voltmeter.adc_raw * -1.0; // wrong polarity ?!`

**Comment by Sarah-C** [comment]
Yeah, I'm getting that too!

Interestingly, the getValue() function works just fine.

The demo code shows how to grab a sequence of raw ADC values, and average them out, and apply the calibration to it. But I've found the library function "getValue" works just fine. The demo's not working around anything, just there for information for the coder. We don't NEED to do it like that.

Also - it measures 0 to 32 volts.... not 36 as shown on the label.

The adc_raw value is a signed integer: int16_t adc_raw;
I figure that's to read -36 volts to +36 volts.

But the device doesn't do that! adc_raw values goes from 65535 for 0 volts, to 0 for 32 volts.. it doesn't read negative voltages at all! (in my version just bought in August 2022)
So just convert the int16_t :     uint16_t unsignedADC_Raw = adc_raw;

I discovered some facts:
1: Set the sample time to RATE_8 - the SLOWEST and most stable readings.
2: PAG_256 needs to be set for the gain, NOT PAG_512. 

This then gives the full range of 0 to 32v to THREE decimal places on the whole range.

My device does NOT read negative voltages. It reads 0 to 32 volts to the millivolt.                  
I figured that out from some real world measurements, I read UP TO 8 volts can be sensed with PAG_256, but that is NOT the case with the module as it is built! It's specifically designed to measure voltage to 3 decimal places, with an accuracy of a millivolt. 0.000??.

 At 10.009836 volts the raw ADC was 20395                  
 At 10.009345 volts the raw ADC was 20394             
It's easy to see that 10v = 20,000 so 30v = 60,000 well within the 65535 value of a 2 byte word.                       
And therefore, each single bit rise = 0.000491 volts (that half a millivolt the tec-specs mention - CONFIRMED)              
So the meaningful digits for the entire 32v range are xx.xxx                                

Running the maths for that "resolution per ADC bit", I get:                      
65535 (2 bytes) max * 0.000491 = 32.177685 volts maximum.                   
Highest accuracy reading of 3 decimal places, and up to 30 volts = PAG_256
(The circuit's not built to read higher volts? Setting it less than this maximum gain only reduces accuracy!)

**Comment by Sarah-C** [comment]
The ENTIRE M5StickC plus program for 0  to 32 volts to 3 decimal places therefore can be written as 
(at least on these new devices that don't read negative voltages!):

```

#include "M5StickCPlus.h"
#include "M5_ADS1115.h"

ADS1115 voltmeter;

void setup() {
  M5.begin();
  Wire.begin();
  voltmeter.setMode(SINGLESHOT);
  voltmeter.setRate(RATE_8); // Lowest most stable read time.
  voltmeter.setGain(PAG_256); // Most sensitive detection.
  M5.Lcd.fillScreen(BLACK);
  M5.Lcd.setTextFont(2);
  M5.Lcd.setTextSize(3);
  M5.Lcd.setRotation(3);
  M5.Lcd.setTextColor(WHITE, BLACK);
  //M5.Lcd.fillRect(65, 10, 5, 10, BLACK);
}

void loop(void) {
  double volts = 0;
  volts = voltmeter.getValue() / 1000.0;
  if(volts < 0.000001) volts = 0.0;
  M5.Lcd.setCursor(30, 40);
  M5.Lcd.printf("%.3lf v   ", volts); 
}
```

**Comment by ArminPP** [comment]
Thank you for your detailed investigations!

**Comment by TinyuZhao** [comment]
fixed.
