### ISSUE TITLE
Compilation error: 'ADS1115' does not name a type; did you mean 'ADC_11db'?

### ISSUE THREAD

**Issue by Onzeisnottwice** [m5stack/M5-ADS1115#7]
<img width="906" alt="Screenshot 2024-04-27 at 12 52 38" src="https://github.com/m5stack/M5-ADS1115/assets/50077138/74c1fe76-bff2-426d-aa67-840d3350bebc">
Hi,
Try to compile this code for M5Atom, but get the error : Compilation error: 'ADS1115' does not name a type; did you mean 'ADC_11db'? on this piece of code :ADS1115 Vmeter;
Any sugestions on what i am doing wrong. In installed #include "M5_ADS1115.h" version 0.0.2.
This is the code:

Edit : also interesting lib manager Arduino sais version 0.0.2 but the compiler says it used version 0.0.1

`
#include "M5_ADS1115.h"

#define M5_UNIT_VMETER_I2C_ADDR             0x49
#define M5_UNIT_VMETER_EEPROM_I2C_ADDR      0x53
#define M5_UNIT_VMETER_PRESSURE_COEFFICIENT 0.015918958F

ADS1115 Vmeter;

float resolution         = 0.0;
float calibration_factor = 0.0;

void setup() {
    Serial.begin(115200);
    while (!Vmeter.begin(&Wire, M5_UNIT_VMETER_I2C_ADDR, 26, 32, 400000U)) {
        Serial.println("Unit Vmeter Init Fail");
        delay(1000);
    }
    Vmeter.setEEPROMAddr(M5_UNIT_VMETER_EEPROM_I2C_ADDR);
    Vmeter.setMode(ADS1115_MODE_SINGLESHOT);
    Vmeter.setRate(ADS1115_RATE_8);
    Vmeter.setGain(ADS1115_PGA_512);
    // | PGA      | Max Input Voltage(V) |
    // | PGA_6144 |        128           |
    // | PGA_4096 |        64            |
    // | PGA_2048 |        32            |
    // | PGA_512  |        16            |
    // | PGA_256  |        8             |

    resolution = Vmeter.getCoefficient() / M5_UNIT_VMETER_PRESSURE_COEFFICIENT;
    calibration_factor = Vmeter.getFactoryCalibration();
}

void loop() {
    int16_t adc_raw = Vmeter.getSingleConversion();
    float voltage   = adc_raw * resolution * calibration_factor;
    Serial.printf("Cal ADC:%.0f\n", adc_raw * calibration_factor);
    Serial.printf("Cal Voltage:%.2f mV\n", voltage);
    Serial.printf("Raw ADC:%d\n\n", adc_raw);
}`

**Comment by TinyuZhao** [comment]
Unable to reproduce, please try updating the library and try again.
<img width="1411" alt="image" src="https://github.com/m5stack/M5-ADS1115/assets/44396641/2d4c1c81-4323-4323-b6cb-ef59a8b0100d">

**Comment by TinyuZhao** [comment]
Please update your M5-ADS1115 library.

**Comment by Onzeisnottwice** [comment]
Sorry for my. late response, caught up in another project.
Indeed, updating my libs did the trick.
Thanks

**Comment by TinyuZhao** [comment]
I am glad to be able to help you.
