### ISSUE TITLE
Generic library error

### ISSUE THREAD

**Issue by NikolasRec** [m5stack/M5-ADS1115#8]
In file included from c:\Users\Minoas\Documents\Arduino\libraries\M5GFX\src/M5GFX.h:19:0,
                 from c:\Users\Minoas\Documents\Arduino\libraries\M5Unified\src/M5Unified.hpp:19,
                 from c:\Users\Minoas\Documents\Arduino\libraries\M5Unified\src/M5Unified.h:5,
                 from C:\Users\Minoas\Documents\Arduino\sketch_jun14a\sketch_jun14a.ino:17:
c:\Users\Minoas\Documents\Arduino\libraries\M5GFX\src/lgfx/v1/platforms/device.hpp:94:10: fatal error: arduino_default/Bus_SPI.hpp: No such file or directory
 #include "arduino_default/Bus_SPI.hpp"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: exit status 1

**Comment by TinyuZhao** [comment]
Please specify all configurations, cannot reproduce.
<img width="1411" alt="image" src="https://github.com/m5stack/M5-ADS1115/assets/44396641/70b2a04d-44e3-488c-8b10-d6545fc615f1">

**Comment by SalilpUBR** [comment]
Hi Im having same issue with M5Stack U162 emaxple code

**Comment by TinyuZhao** [comment]
Upgrade to the latest M5Unified and M5GFX repositories and give it a try

**Comment by SalilpUBR** [comment]
Hi Tinyu, 
I'm Still Having Same Issue in M5GFX Example Code.
![Capture](https://github.com/m5stack/M5-ADS1115/assets/173792763/de0d9f7a-96f2-4058-bfb3-5d67fdda25d9)

**Comment by TinyuZhao** [comment]
> Hi Tinyu, 嗨，Tinyu， I'm Still Having Same Issue in M5GFX Example Code.我在 M5GFX 示例代码中仍然遇到相同的问题。 ![Capture](https://private-user-images.githubusercontent.com/173792763/343021765-de0d9f7a-96f2-4058-bfb3-5d67fdda25d9.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzODU1MTMsIm5iZiI6MTcxOTM4NTIxMywicGF0aCI6Ii8xNzM3OTI3NjMvMzQzMDIxNzY1LWRlMGQ5ZjdhLTk2ZjItNDA1OC1iZmIzLTVkNjdmZGRhMjVkOS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQwNzAwMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzEyZDMwMjJhY2MyMDg0NzY0OGUxYzk1ZTc2ZDMwNGI0ZGQ5MTNiNDYwMDY1Njk5OTUwZDA5OTliNmUyNmY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AfyjJrZLD-zc4I_mHDpJyYMxDi9l_2aK5Y8ISq3QfgY)

This issue does not belong to this repository.

**Comment by SoLongSidekick** [comment]
Uhhh... why was this closed? I see no solution and I just ran into this problem.

**Comment by TinyuZhao** [comment]
> Uhhh... why was this closed? I see no solution and I just ran into this problem.

emmm The warehouse where the error occurred probably does not belong to M5.

<img width="626" alt="image" src="https://github.com/user-attachments/assets/56cb3ed1-6846-47f5-ba5b-17ec57482e67" />

**Comment by RealZogzog** [comment]
And yet I have the same problem and no solutions...
